// <auto-generated />
using System;
using Arturia.ShortLink.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arturia.ShortLink.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.ApiKey", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<ulong>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("key_hash")
                        .UseCollation("ascii_bin");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("key_prefix")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<ulong>("WorkspaceId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("fk_api_key_creator");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("uk_key_hash");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .HasDatabaseName("idx_ws_created");

                    b.ToTable("sys_api_key", (string)null);
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.LinkAccessLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("BotName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("bot_name");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("browser");

                    b.Property<string>("City")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("未知")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("桌面端")
                        .HasColumnName("device_type");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsBot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_bot");

                    b.Property<ulong>("LinkId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("link_id");

                    b.Property<string>("Os")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("os");

                    b.Property<string>("Referer")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasDefaultValue("")
                        .HasColumnName("referer");

                    b.Property<string>("RefererDomain")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasDefaultValue("")
                        .HasColumnName("referer_domain");

                    b.Property<string>("Region")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("region");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasDefaultValue("")
                        .HasColumnName("user_agent");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("utm_campaign");

                    b.Property<string>("UtmContent")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("utm_content");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("utm_medium");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("utm_source");

                    b.Property<string>("UtmTerm")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("utm_term");

                    b.Property<string>("VisitorHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("visitor_hash")
                        .UseCollation("ascii_bin");

                    b.Property<ulong>("WorkspaceId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("LinkId", "CreatedAt")
                        .HasDatabaseName("idx_link_time");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .HasDatabaseName("idx_ws_time");

                    b.HasIndex("WorkspaceId", "LinkId")
                        .HasDatabaseName("fk_log_workspace_link");

                    b.HasIndex("LinkId", "VisitorHash", "CreatedAt")
                        .HasDatabaseName("idx_link_visitor_time");

                    b.HasIndex("WorkspaceId", "IsBot", "CreatedAt")
                        .HasDatabaseName("idx_ws_bot_time");

                    b.HasIndex("WorkspaceId", "UtmCampaign", "CreatedAt")
                        .HasDatabaseName("idx_utm_campaign_time");

                    b.ToTable("link_access_log", null, t =>
                        {
                            t.HasCheckConstraint("chk_log_is_bot", "`is_bot` IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.LinkDomain", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("varchar(253)")
                        .HasColumnName("domain")
                        .UseCollation("ascii_bin");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("SslStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("ssl_status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("verification_code")
                        .UseCollation("ascii_bin");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IsSystem")
                        .HasName("uk_domain_id_system");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("uk_domain");

                    b.HasIndex("VerificationCode")
                        .IsUnique()
                        .HasDatabaseName("uk_domain_verification_code");

                    b.ToTable("link_domain", null, t =>
                        {
                            t.HasCheckConstraint("chk_domain_is_system", "`is_system` IN (0, 1)");

                            t.HasCheckConstraint("chk_domain_is_verified", "`is_verified` IN (0, 1)");

                            t.HasCheckConstraint("chk_domain_normalized", "CHAR_LENGTH(`domain`) BETWEEN 1 AND 253 AND `domain` = LOWER(`domain`) AND `domain` NOT LIKE '%://%' AND `domain` NOT LIKE '%/%' AND `domain` NOT LIKE '%:%' AND RIGHT(`domain`, 1) <> '.'");

                            t.HasCheckConstraint("chk_domain_ssl_status", "`ssl_status` IN ('Active', 'Pending', 'Error')");
                        });
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.RiskRule", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("contains")
                        .HasColumnName("match_type");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("pattern");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasDefaultValue("")
                        .HasColumnName("reason");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("rule_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("system")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("fk_risk_rule_creator");

                    b.HasIndex("IsActive", "RuleType")
                        .HasDatabaseName("idx_rule_active_type");

                    b.HasIndex("RuleType", "Pattern")
                        .IsUnique()
                        .HasDatabaseName("uk_rule_type_pattern");

                    b.ToTable("risk_rule", null, t =>
                        {
                            t.HasCheckConstraint("chk_risk_is_active", "`is_active` IN (0, 1)");

                            t.HasCheckConstraint("chk_risk_match_type", "`match_type` IN ('exact', 'suffix', 'contains', 'regex')");

                            t.HasCheckConstraint("chk_risk_rule_type", "`rule_type` IN ('blocked_protocol', 'blocked_domain', 'blocked_keyword', 'reserved_slug', 'bot_user_agent')");
                        });
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.ShortLink", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("ActiveSlug")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("active_slug")
                        .HasComputedColumnSql("CASE WHEN `deleted_at` IS NULL THEN `slug` ELSE NULL END", true)
                        .UseCollation("ascii_bin");

                    b.Property<DateTime?>("BannedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("banned_at");

                    b.Property<ulong?>("BannedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("banned_by");

                    b.Property<string>("BannedReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("banned_reason");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<ulong>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<ulong?>("DeletedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<ulong>("DomainId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("domain_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("original_url");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("slug")
                        .UseCollation("ascii_bin");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("")
                        .HasColumnName("title");

                    b.Property<ulong>("TotalClicks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasDefaultValue(0ul)
                        .HasColumnName("total_clicks");

                    b.Property<ulong>("TotalUniqueVisitors")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasDefaultValue(0ul)
                        .HasColumnName("total_unique_visitors");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("utm_campaign");

                    b.Property<string>("UtmContent")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("utm_content");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("utm_medium");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("utm_source");

                    b.Property<string>("UtmTerm")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("utm_term");

                    b.Property<ulong>("WorkspaceId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("uk_workspace_link");

                    b.HasIndex("BannedBy")
                        .HasDatabaseName("fk_link_banner");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("idx_created_by");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_deleted_at");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("fk_link_deleter");

                    b.HasIndex("DomainId", "ActiveSlug")
                        .IsUnique()
                        .HasDatabaseName("uk_domain_active_slug");

                    b.HasIndex("WorkspaceId", "DomainId")
                        .HasDatabaseName("fk_link_workspace_domain");

                    b.HasIndex("WorkspaceId", "IsBanned", "CreatedAt")
                        .HasDatabaseName("idx_ws_banned_created");

                    b.HasIndex("WorkspaceId", "IsEnabled", "CreatedAt")
                        .HasDatabaseName("idx_ws_enabled_created");

                    b.ToTable("short_link", null, t =>
                        {
                            t.HasCheckConstraint("chk_link_is_banned", "`is_banned` IN (0, 1)");

                            t.HasCheckConstraint("chk_link_is_enabled", "`is_enabled` IN (0, 1)");

                            t.HasCheckConstraint("chk_link_slug", "`slug` REGEXP '^[0-9A-Za-z_-]{3,32}$'");
                        });
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasDefaultValue("")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("email");

                    b.Property<sbyte>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("status");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("nickname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uk_email");

                    b.ToTable("sys_user", null, t =>
                        {
                            t.HasCheckConstraint("chk_user_status", "`status` IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.Workspace", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<ulong>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<int>("MaxDomains")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3)
                        .HasColumnName("max_domains");

                    b.Property<int>("MaxLinks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1000)
                        .HasColumnName("max_links");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<string>("PlanTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("free")
                        .HasColumnName("plan_tier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("idx_created_by");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uk_slug");

                    b.ToTable("sys_workspace", null, t =>
                        {
                            t.HasCheckConstraint("chk_workspace_slug", "`slug` REGEXP '^[a-z0-9]([a-z0-9-]{1,30}[a-z0-9])$'");
                        });
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.WorkspaceDomain", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<ulong?>("CustomDomainId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("custom_domain_id")
                        .HasComputedColumnSql("CASE WHEN `is_system` = 0 THEN `domain_id` ELSE NULL END", true);

                    b.Property<ulong>("DomainId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("domain_id");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_system");

                    b.Property<ulong?>("PrimaryWorkspaceId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("primary_workspace_id")
                        .HasComputedColumnSql("CASE WHEN `is_primary` = 1 THEN `workspace_id` ELSE NULL END", true);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<ulong>("WorkspaceId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "DomainId")
                        .HasName("uk_ws_domain");

                    b.HasIndex("CustomDomainId")
                        .IsUnique()
                        .HasDatabaseName("uk_custom_domain_owner");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("idx_binding_domain");

                    b.HasIndex("PrimaryWorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("uk_primary_workspace");

                    b.HasIndex("DomainId", "IsSystem")
                        .HasDatabaseName("fk_binding_domain_type");

                    b.ToTable("workspace_domain", null, t =>
                        {
                            t.HasCheckConstraint("chk_binding_is_primary", "`is_primary` IN (0, 1)");

                            t.HasCheckConstraint("chk_binding_is_system", "`is_system` IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.WorkspaceInvitation", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("accepted_at");

                    b.Property<ulong?>("AcceptedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("accepted_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<ulong>("InvitedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("invited_by");

                    b.Property<string>("PendingEmail")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("pending_email")
                        .HasComputedColumnSql("CASE WHEN `status` = 'pending' THEN LOWER(`email`) ELSE NULL END", true);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("member")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<ulong>("WorkspaceId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedBy")
                        .HasDatabaseName("fk_invitation_acceptor");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("fk_invitation_inviter");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uk_invitation_token_hash");

                    b.HasIndex("WorkspaceId", "PendingEmail")
                        .IsUnique()
                        .HasDatabaseName("uk_ws_pending_email");

                    b.HasIndex("Email", "Status", "ExpiresAt")
                        .HasDatabaseName("idx_invitation_email_status");

                    b.ToTable("workspace_invitation", null, t =>
                        {
                            t.HasCheckConstraint("chk_invitation_role", "`role` IN ('admin', 'member')");

                            t.HasCheckConstraint("chk_invitation_status", "`status` IN ('pending', 'accepted', 'expired', 'revoked')");
                        });
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.WorkspaceMember", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("member")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.Property<ulong>("WorkspaceId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WorkspaceId")
                        .HasDatabaseName("idx_user_ws");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uk_ws_user");

                    b.ToTable("sys_workspace_member", null, t =>
                        {
                            t.HasCheckConstraint("chk_member_role", "`role` IN ('owner', 'admin', 'member')");
                        });
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("Arturia.ShortLink.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_creator");

                    b.HasOne("Arturia.ShortLink.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_workspace");
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.LinkAccessLog", b =>
                {
                    b.HasOne("Arturia.ShortLink.Domain.Entities.ShortLink", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "LinkId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_log_workspace_link");
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.RiskRule", b =>
                {
                    b.HasOne("Arturia.ShortLink.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_risk_rule_creator");
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.ShortLink", b =>
                {
                    b.HasOne("Arturia.ShortLink.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("BannedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_link_banner");

                    b.HasOne("Arturia.ShortLink.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_link_creator");

                    b.HasOne("Arturia.ShortLink.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_link_deleter");

                    b.HasOne("Arturia.ShortLink.Domain.Entities.WorkspaceDomain", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "DomainId")
                        .HasPrincipalKey("WorkspaceId", "DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_link_workspace_domain");
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("Arturia.ShortLink.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_creator");
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.WorkspaceDomain", b =>
                {
                    b.HasOne("Arturia.ShortLink.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_binding_workspace");

                    b.HasOne("Arturia.ShortLink.Domain.Entities.LinkDomain", null)
                        .WithMany()
                        .HasForeignKey("DomainId", "IsSystem")
                        .HasPrincipalKey("Id", "IsSystem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_binding_domain_type");
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.WorkspaceInvitation", b =>
                {
                    b.HasOne("Arturia.ShortLink.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AcceptedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_invitation_acceptor");

                    b.HasOne("Arturia.ShortLink.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitation_inviter");

                    b.HasOne("Arturia.ShortLink.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitation_workspace");
                });

            modelBuilder.Entity("Arturia.ShortLink.Domain.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("Arturia.ShortLink.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_user");

                    b.HasOne("Arturia.ShortLink.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_workspace");
                });
#pragma warning restore 612, 618
        }
    }
}
